# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 15:17
from __future__ import unicode_literals

from django.db import migrations


# APPSEMBLER MIGRATION


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20171207_0259'),
        ('organizations', '0008_auto_20170321_0752'),
    ]

    operations = [
    ]
