# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-27 08:27
from __future__ import unicode_literals

from django.db import migrations

# APPSEMBLER MIGRATION


class Migration(migrations.Migration):
    """
    Merge Tahoe and upstream migrations.

    Tech-Debt: This is a Tahoe tech-debt that we 
               got stuck into and need to clean some day.
    """

    dependencies = [
        ('organizations', '0007_historicalorganization'),
        ('organizations', '0009_merge_20181113_1517_appsembler'),
    ]

    operations = []
